Repository PROJECT-LAB18/POTATO-MARKET, pull requests merged in 2023-04, with the labels that each got.

#143 [Bugfix#001] 에러 수정 작업
  potato-market/src/pages/MyPage.jsx
  potato-market/src/pages/SignUp.jsx
Labels: 🐞bugfix, 🔨enhancement

#148 [Refact] addPhoto 컴포넌트 input file button, input label 명시적인 연결 방법으로 변경
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/main.jsx
  potato-market/src/pages/HotArticles.jsx
  potato-market/src/pages/HotArticles/Filter.jsx
  potato-market/src/pages/HotArticles/RegionSelect.jsx
  potato-market/src/pages/WriteArticle.jsx
Labels: 🔨enhancement

#149 [migration] FormInput.tsx 변환
  potato-market/src/components/FormInput.tsx
Labels: 🧵migration

#157 [migration]productdetail tsx 설정
  potato-market/src/assets/velog.svg
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/comment.tsx
  potato-market/src/pages/productdetail.tsx
  potato-market/src/stores/userAuth.jsx
Labels: 🧵migration

#158 [migration]SignUp.tsx 완료
  potato-market/src/components/FormInput.tsx
  potato-market/src/components/FormTerms.tsx
  potato-market/src/pages/SignUp.tsx
  potato-market/src/styles/FormButton.tsx
Labels: 🧵migration

#167 [migration] SignIn / LoginState / Popup / MyPage / LogoutButton
  potato-market/src/components/LoginState.jsx
  potato-market/src/components/LoginState.tsx
  potato-market/src/components/LogoutButton.jsx
  potato-market/src/components/LogoutButton.tsx
  potato-market/src/components/Popup.tsx
  potato-market/src/pages/MyPage.tsx
  potato-market/src/pages/SignIn.tsx
Labels: 🧵migration

#173 [refact] 성능개선 및 코드 가독성 개선 #172
  potato-market/.eslintrc.cjs
  potato-market/.prettierrc.cjs
  potato-market/index.html
  potato-market/package-lock.json
  potato-market/package.json
  potato-market/src/App.jsx
  potato-market/src/assets/product-photo.png
  potato-market/src/assets/test/pingu-memo.jpg
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/Chat/ChatInfo.jsx
  potato-market/src/components/Chat/ChatList.jsx
  potato-market/src/components/Chat/HambugerMenu.jsx
  potato-market/src/components/Chat/MainChat.jsx
  potato-market/src/components/FilterProducts.jsx
  potato-market/src/components/Footer.jsx
  potato-market/src/components/FormInput.jsx
  potato-market/src/components/FormInputAddress.jsx
  potato-market/src/components/FormTerms.jsx
  potato-market/src/components/Header.jsx
  potato-market/src/components/LoadingSpinner.jsx
  potato-market/src/components/LoginState.jsx
  potato-market/src/components/LogoutButton.jsx
  potato-market/src/components/NotFound.jsx
  potato-market/src/components/Popup.jsx
  potato-market/src/components/Recommend.jsx
  potato-market/src/components/Toggle.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/comment.jsx
  potato-market/src/components/product.jsx
  potato-market/src/components/swiper.jsx
  potato-market/src/firebase.js
  potato-market/src/lib/_ex.jsx
  potato-market/src/main.jsx
  potato-market/src/pages/Chat.jsx
  potato-market/src/pages/ChatPage.jsx
  potato-market/src/pages/Home.jsx
  potato-market/src/pages/HotArticles.jsx
  potato-market/src/pages/MyPage.jsx
  potato-market/src/pages/SignIn.jsx
  potato-market/src/pages/SignUp.jsx
  potato-market/src/pages/WriteArticle.jsx
  potato-market/src/pages/productdetail.jsx
  potato-market/src/stores/onChat.js
  potato-market/src/stores/state.js
  potato-market/src/stores/toggle.js
  potato-market/src/stores/userAuth.js
  potato-market/src/styles/ContainerGlobalStyle.js
  potato-market/src/styles/CustomButton.js
  potato-market/src/styles/FormButton.js
  potato-market/src/styles/Global.js
  potato-market/src/styles/ProductList.js
  potato-market/src/styles/Wrapper.js
  potato-market/src/styles/chatInfoStyle.module.css
  potato-market/src/styles/chatLayout.module.css
  potato-market/src/styles/mainChatStyle.module.css
  potato-market/src/utils/moneyUnit.js
  potato-market/vite.config.js
Labels: 🔨enhancement
