Repository PROJECT-LAB18/POTATO-MARKET, pull requests merged in 2023-03, with the labels that each got.

#38 [#8] (로그인) 기본 마크업 & 스타일링
  potato-market/src/App.jsx
  potato-market/src/components/FormInput.jsx
  potato-market/src/pages/SignIn.jsx
  potato-market/src/styles/FormButton.js
  potato-market/src/styles/Global.js
Labels: 🖌markup&styles

#39 [feature , markup&styles #30 ] 스와이퍼 추가 및 , 프로덕츠디테일 마크업
  potato-market/package-lock.json
  potato-market/package.json
  potato-market/src/App.jsx
  potato-market/src/assets/test/핑구 메모.jpg
  potato-market/src/components/_ex.jsx
  potato-market/src/components/product.jsx
  potato-market/src/pages/productdetail.jsx
Labels: 🖌markup&styles

#40 [setting] 페이지 임의로 생성 및 router 연결
  potato-market/src/App.jsx
  potato-market/src/components/Footer.jsx
  potato-market/src/components/Header.jsx
  potato-market/src/main.jsx
  potato-market/src/pages/Chat.jsx
  potato-market/src/pages/Home.jsx
  potato-market/src/pages/HotArticles.jsx
  potato-market/src/pages/MyArticle.jsx
  potato-market/src/pages/SignUp.jsx
  potato-market/src/pages/WriteArticle.jsx
  potato-market/src/pages/_ex.jsx
Labels: ⚙️setting

#41 [#20 #21] 상품 목록 마크업 & 스타일링
  potato-market/src/assets/icon-arrow-under.svg
  potato-market/src/pages/HotArticles/Filter.jsx
  potato-market/src/pages/HotArticles/HotArticles.jsx
  potato-market/src/pages/HotArticles/RegionSelect.jsx
  potato-market/src/styles/ContainerGlobalStyle.js
Labels: 🖌markup&styles

#47 [Productdetail#30]이미지클릭시 확대 이미지창[모달] 구현
  potato-market/src/assets/closebutton.svg
  potato-market/src/components/product.jsx
  potato-market/src/components/swiper.jsx
  potato-market/src/pages/productdetail.jsx
Labels: ✨feature

#48 [#43, #44] 게시글 작성 마크업 / 스타일링
  potato-market/.eslintrc.cjs
  potato-market/src/assets/icon-add-photo.svg
  potato-market/src/assets/icon-close-button.svg
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/pages/WriteArticle.jsx
Labels: 🖌markup&styles

#52 [#1] Header 1차 마크업 & 스타일링 #1
  potato-market/src/App.jsx
  potato-market/src/assets/defaultProfile.svg
  potato-market/src/assets/logo(symbol+name).svg
  potato-market/src/assets/logo.svg
  potato-market/src/pages/Header.jsx
  potato-market/src/styles/Global.js
Labels: 🖌markup&styles

#51 [#19] Footer 마크업 & 스타일링 1차 완성 #19
  potato-market/src/assets/facebook.svg
  potato-market/src/assets/github.svg
  potato-market/src/assets/instagram.svg
  potato-market/src/assets/naverblog.svg
  potato-market/src/assets/verticalbar.svg
  potato-market/src/assets/youtube.svg
  potato-market/src/components/Footer.jsx
Labels: 🖌markup&styles

#53 [#2] Home 화면 기본 마크업 & 스타일링 #2
  potato-market/src/pages/Home.jsx
Labels: 🖌markup&styles

#58 [#49, #54] 상품 목록 렌더링 & 게시글 작성 기능 구현
  potato-market/src/assets/loading-spinner.gif
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/LoadingSpinner.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/product.jsx
  potato-market/src/main.jsx
  potato-market/src/pages/HotArticles/HotArticles.jsx
  potato-market/src/pages/WriteArticle.jsx
  potato-market/src/styles/Global.js
Labels: ✨feature

#57 [#11 #12 #17 #18 #50] 로그인/회원가입 기능 1차 구현
  potato-market/package-lock.json
  potato-market/package.json
  potato-market/src/App.jsx
  potato-market/src/components/DaumPostCodeEmbed.jsx
  potato-market/src/components/FormInput.jsx
  potato-market/src/components/FormTerms.jsx
  potato-market/src/components/LogoutButton.jsx
  potato-market/src/components/Popup.jsx
  potato-market/src/components/Postcode.jsx
  potato-market/src/pages/SignIn.jsx
  potato-market/src/pages/SignUp.jsx
Labels: ✨feature

#77 [#22, #31] 조회수 기능 & 게시글 클릭 시 해당되는 게시글 디테일 페이지로 이동 기능 구현
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/Footer.jsx
  potato-market/src/components/LoadingSpinner.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/product.jsx
  potato-market/src/main.jsx
  potato-market/src/pages/HotArticles/HotArticles.jsx
  potato-market/src/pages/productdetail.jsx
  potato-market/src/styles/ContainerGlobalStyle.js
  potato-market/src/utils/moneyUnit.js
Labels: ✨feature

#79 [#12, #55] 회원가입 프로필 사진 등록 + 회원가입 성공 시 팝업 노출 후 이전 페이지 라우팅 #78
  potato-market/src/App.jsx
  potato-market/src/components/FormInput.jsx
  potato-market/src/components/Popup.jsx
  potato-market/src/firebase.js
  potato-market/src/pages/SignIn.jsx
  potato-market/src/pages/SignUp.jsx
Labels: ✨feature

#46 Chat#32
  potato-market/package-lock.json
  potato-market/package.json
  potato-market/src/App.jsx
  potato-market/src/assets/alias.png
  potato-market/src/assets/chat_emty.svg
  potato-market/src/assets/check.svg
  potato-market/src/assets/check_activate.svg
  potato-market/src/assets/default_profile.png
  potato-market/src/assets/hambuger_menu.svg
  potato-market/src/assets/imogi.png
  potato-market/src/assets/inpu_file.png
  potato-market/src/assets/question.svg
  potato-market/src/assets/제품사진.png
  potato-market/src/components/Chat/ChatInfo.jsx
  potato-market/src/components/Chat/ChatList.jsx
  potato-market/src/components/Chat/HambugerMenu.jsx
  potato-market/src/components/Chat/MainChat.jsx
  potato-market/src/pages/ChatPage.jsx
  potato-market/src/styles/chatInfoStyle.module.css
  potato-market/src/styles/chatLayout.module.css
  potato-market/src/styles/mainChatStyle.module.css
  potato-market/vite.config.js
Labels: 🖌markup&styles

#81 [#55] 회원가입 폼 프로필 사진 등록 기능 구현 (2차)
  potato-market/src/components/FormInput.jsx
  potato-market/src/pages/SignUp.jsx
Labels: ✨feature, 🖌markup&styles

#84 [#18] 주소 api 연동하여 회원가입 시 주소 선택 후 input 필드에 가져오기 & 가입완료 시 파이어베이스 db에 추가
  potato-market/package-lock.json
  potato-market/src/components/DaumPostCodeEmbed.jsx
  potato-market/src/components/FormInput.jsx
  potato-market/src/components/FormInputAddress.jsx
  potato-market/src/components/Postcode.jsx
  potato-market/src/pages/SignUp.jsx
Labels: ✨feature

#82 [#12] 회원가입/로그인 파이어베이스 코드 정리 및 공통화
  potato-market/src/App.jsx
  potato-market/src/firebase.js
  potato-market/src/pages/SignIn.jsx
  potato-market/src/pages/SignUp.jsx
Labels: 🔨enhancement

#83 [#26] 사용자 정보, 상품 연결
  potato-market/index.html
  potato-market/src/App.jsx
  potato-market/src/assets/icon_temp4.svg
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/product.jsx
  potato-market/src/components/swiper.jsx
  potato-market/src/main.jsx
  potato-market/src/pages/WriteArticle.jsx
  potato-market/src/pages/productdetail.jsx
  potato-market/src/stores/userAuth.js
Labels: ✨feature

#88 Sign up#17 #86 #87
  potato-market/src/components/FormInput.jsx
  potato-market/src/firebase.js
  potato-market/src/pages/SignUp.jsx
Labels: ✨feature

#85 [#55] 프로필 사진 미업로드 시, 기본 이미지가 적용되도록 처리
  potato-market/src/pages/SignUp.jsx
Labels: 🐞bugfix, ✨feature

#90 [#67] 지역 정보 연결 및 게시글 수정&삭제 기능 구현
  potato-market/src/App.jsx
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/product.jsx
  potato-market/src/firebase.js
  potato-market/src/pages/HotArticles/HotArticles.jsx
  potato-market/src/pages/WriteArticle.jsx
  potato-market/src/pages/productdetail.jsx
  potato-market/src/stores/userAuth.js
  potato-market/src/styles/Global.js
Labels: ✨feature

#91 [#60] Home 화면에 인기 매물 8개 노출
  potato-market/src/pages/Home.jsx
  potato-market/src/pages/HotArticles/HotArticles.jsx
Labels: ✨feature

#94 [feature] 헤더 페이지 간 이동 구현 #6
  potato-market/src/components/Header.jsx
Labels: ✨feature

#95 [#93] 이미지 최적화 적용 : 프로필 사진
  potato-market/package-lock.json
  potato-market/package.json
  potato-market/src/components/FormInput.jsx
  potato-market/src/pages/SignUp.jsx
Labels: 🔨enhancement

#98 [#97] "나의매물조회" => "마이페이지" 확장
  potato-market/src/main.jsx
  potato-market/src/pages/MyArticle.jsx
  potato-market/src/pages/MyPage.jsx
Labels: ✨feature, 🖌markup&styles

#99 [chat] 채팅 팝업창 마크업/스타일링 & 기능 구현
  .vscode/settings.json
  potato-market/index.html
  potato-market/src/App.jsx
  potato-market/src/assets/chat/chat-bg.svg
  potato-market/src/assets/chat/chat-close-button.svg
  potato-market/src/assets/chat/chat-send.svg
  potato-market/src/assets/chat/chat_reset.svg
  potato-market/src/components/Header.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/comment.jsx
  potato-market/src/main.jsx
  potato-market/src/stores/onChat.js
  potato-market/src/styles/Global.js
Labels: ✨feature, 🖌markup&styles

#112 [#103, chat] chat 키보드 이벤트 추가 / 게시글 작성 이미지 최적화 및 전송 이슈 등
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/comment.jsx
  potato-market/src/styles/Global.js
Labels: ✨feature, 🔨enhancement

#115 [feature] 비로그인시 보여주는 화면 컴포넌트화 시켜서 마이페이지에도 적용 + 비로그인 채팅 프로필이랑 닉네임(수상한 …
  potato-market/src/components/comment.jsx
  potato-market/src/components/loginNeed.jsx
  potato-market/src/pages/MyPage.jsx
  potato-market/src/pages/WriteArticle.jsx
Labels: ✨feature

#119 [Header#104, #96] 컴포넌트 분리, err img 추가 스타일 조건부 렌더링
  potato-market/index.html
  potato-market/src/components/FilterProducts.jsx
  potato-market/src/pages/HotArticles/HotArticles.jsx
  potato-market/src/styles/Wrapper.js
Labels: ✨feature, 🖌markup&styles

#120 [#116] 에러 페이지 / 라우터 연결 / 뒤로가기 버튼 추가
  potato-market/src/assets/errorImg.svg
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/NotFound.jsx
  potato-market/src/main.jsx
  potato-market/src/pages/HotArticles/HotArticles.jsx
Labels: 🖌markup&styles

#121 [test] Recoil-persist를 이용해서 유저정보 로컬스토리지에 넣기
  potato-market/package-lock.json
  potato-market/package.json
  potato-market/src/App.jsx
  potato-market/src/components/LogoutButton.jsx
  potato-market/src/components/comment.jsx
  potato-market/src/main.jsx
  potato-market/src/pages/SignUp.jsx
  potato-market/src/pages/productdetail.jsx
  potato-market/src/stores/userAuth.js
Labels: 🧪test

#122 [feature] 댓글 기능 마크업 스타일링 기능까지 구현#118
  potato-market/src/components/Recommend.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/comment.jsx
  potato-market/src/components/product.jsx
  potato-market/src/pages/productdetail.jsx
Labels: ✨feature, 🖌markup&styles

#127 [bugfix] 로그아웃 시, 유저정보 객체 내부 각각 초기화하는 로직으로 변경
  potato-market/src/components/LogoutButton.jsx
Labels: 🐞bugfix

#129 [bugfix] 댓글 input value 있는 상태에서 다른 게시글로 갔을 때 value 초기화 안되는 현상 해결
  potato-market/src/components/Recommend.jsx
Labels: 🐞bugfix

#130 [#97] 마이페이지 신규 기능 생성 : 회원정보 수정 / 회원 탈퇴
  potato-market/src/assets/profile-bg.svg
  potato-market/src/components/FormInput.jsx
  potato-market/src/components/FormTerms.jsx
  potato-market/src/components/Popup.jsx
  potato-market/src/components/Recommend.jsx
  potato-market/src/components/comment.jsx
  potato-market/src/pages/MyPage.jsx
  potato-market/src/pages/SignUp.jsx
Labels: ✨feature, 🖌markup&styles

#131 [css] 프로덕트 디테일 반응형, 비로그인 댓글 사진안보이는거 오류 픽스
  potato-market/src/pages/productdetail.jsx
Labels: 🖌markup&styles

#132 [bugfix] 콘솔 경고 제거, 게시글작성&핫아티클과 푸터 사이 간격 일정하게 조절
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/comment.jsx
  potato-market/src/components/product.jsx
  potato-market/src/pages/productdetail.jsx
  potato-market/src/styles/ContainerGlobalStyle.js
Labels: 🐞bugfix

#133 [#100] [styles] 반응형 코드 수정 : 375px 까지 대응
  potato-market/src/pages/Home.jsx
  potato-market/src/styles/ProductList.js
Labels: 🖌markup&styles

#134 [#100] Header, Footer 반응형 구현
  potato-market/src/assets/hamburger.svg
  potato-market/src/assets/searchIcon.svg
  potato-market/src/assets/xButton.svg
  potato-market/src/components/Footer.jsx
  potato-market/src/components/Header.jsx
  potato-market/src/components/LogoutButton.jsx
Labels: 🖌markup&styles

#137 [bugfix] 채팅 실시간으로 반영안되던 문제(useEffect 수정)
  potato-market/src/components/comment.jsx
Labels: 🐞bugfix

#139 [Bugfix#000] Addphoto x 버튼 경로 수정 / 홈화면에서 채팅창 타이틀 가운데정렬 되는 현상(왼쪽 정렬로 변경) / 채팅, 댓글 빈문자열일 때 전송되지 않도록 변경
  potato-market/src/components/AddPhoto.jsx
  potato-market/src/components/Recommend.jsx
  potato-market/src/components/comment.jsx
  potato-market/src/pages/productdetail.jsx
Labels: 🐞bugfix

#140 [Bugfix] 상품 리스트에 댓글수 표시 & 댓글 순으로 정렬 등
  potato-market/src/components/FilterProducts.jsx
  potato-market/src/components/WriteForm.jsx
  potato-market/src/components/product.jsx
  potato-market/src/pages/Home.jsx
  potato-market/src/pages/MyPage.jsx
  potato-market/src/pages/productdetail.jsx
Labels: 🐞bugfix, ✨feature

#141 [Bugfix] 댓글창, 헤더 input 에 label 추가 / 이미지 태그 alt 미설정한 부분 추가
  potato-market/src/App.jsx
  potato-market/src/assets/banner-main01.png
  potato-market/src/assets/banner-main02.png
  potato-market/src/components/FilterProducts.jsx
  potato-market/src/components/Header.jsx
  potato-market/src/components/NotFound.jsx
  potato-market/src/components/Recommend.jsx
  potato-market/src/pages/Home.jsx
Labels: 🐞bugfix
